import { User } from "./types";

export const SAMPLE_USERS: User[] = [
  {
    id: "1",
    name: "Elena",
    age: 26,
    location: "Kyiv, Ukraine",
    distance: "2,500 km away",
    bio: "Love traveling, photography, and trying new cuisines. Looking for someone to explore the world with.",
    images: [
      "https://picsum.photos/seed/elena1/600/800",
      "https://picsum.photos/seed/elena2/600/800",
    ],
    isVerified: true,
    interests: ["Travel", "Photography", "Coffee"],
    languages: ["Ukrainian", "English"],
  },
  {
    id: "2",
    name: "Mateo",
    age: 29,
    location: "Bogotá, Colombia",
    distance: "4,100 km away",
    bio: "Software engineer by day, salsa dancer by night. Let's practice languages together!",
    images: ["https://picsum.photos/seed/mateo1/600/800"],
    isVerified: true,
    interests: ["Dancing", "Technology", "Hiking"],
    languages: ["Spanish", "English"],
  },
  {
    id: "3",
    name: "Yuki",
    age: 24,
    location: "Tokyo, Japan",
    distance: "8,000 km away",
    bio: "Art student. I love visiting museums and finding hidden cafes.",
    images: [
      "https://picsum.photos/seed/yuki1/600/800",
      "https://picsum.photos/seed/yuki2/600/800",
    ],
    isVerified: false,
    interests: ["Art", "Cafes", "Anime"],
    languages: ["Japanese", "English"],
  },
  {
    id: "4",
    name: "Sarah",
    age: 27,
    location: "London, UK",
    distance: "500 km away",
    bio: "Always planning my next trip. Dog mom. Swipe right if you like bad puns.",
    images: ["https://picsum.photos/seed/sarah1/600/800"],
    isVerified: true,
    interests: ["Dogs", "Comedy", "Travel"],
    languages: ["English", "French"],
  },
  {
    id: "5",
    name: "Liam",
    age: 31,
    location: "Sydney, Australia",
    distance: "16,000 km away",
    bio: "Surfer and coffee enthusiast. Looking for someone to share morning waves with.",
    images: ["https://picsum.photos/seed/liam1/600/800"],
    isVerified: true,
    interests: ["Surfing", "Coffee", "Outdoors"],
    languages: ["English"],
  },
  {
    id: "6",
    name: "Aisha",
    age: 25,
    location: "Dubai, UAE",
    distance: "5,500 km away",
    bio: "Fashion designer. Always looking for inspiration in new places.",
    images: ["https://picsum.photos/seed/aisha1/600/800"],
    isVerified: false,
    interests: ["Fashion", "Design", "Travel"],
    languages: ["Arabic", "English"],
  },
  {
    id: "7",
    name: "Chen",
    age: 28,
    location: "Shanghai, China",
    distance: "9,000 km away",
    bio: "Tech entrepreneur. Love talking about startups and future tech.",
    images: ["https://picsum.photos/seed/chen1/600/800"],
    isVerified: true,
    interests: ["Startups", "Tech", "Reading"],
    languages: ["Mandarin", "English"],
  },
  {
    id: "8",
    name: "Isabella",
    age: 23,
    location: "Rome, Italy",
    distance: "1,400 km away",
    bio: "Culinary student. I'll cook for you if you do the dishes!",
    images: ["https://picsum.photos/seed/isabella1/600/800"],
    isVerified: true,
    interests: ["Cooking", "Food", "Wine"],
    languages: ["Italian", "English"],
  },
  {
    id: "9",
    name: "David",
    age: 30,
    location: "New York, USA",
    distance: "5,500 km away",
    bio: "Musician. Playing gigs around the city. Let's go to a concert.",
    images: ["https://picsum.photos/seed/david1/600/800"],
    isVerified: false,
    interests: ["Music", "Concerts", "Guitar"],
    languages: ["English"],
  },
  {
    id: "10",
    name: "Sofia",
    age: 26,
    location: "Madrid, Spain",
    distance: "1,200 km away",
    bio: "Architect. I love exploring old buildings and sketching.",
    images: ["https://picsum.photos/seed/sofia1/600/800"],
    isVerified: true,
    interests: ["Architecture", "Sketching", "Art"],
    languages: ["Spanish", "English"],
  }
];
